return {
 	top = "#252630",
 	bottom = "#3d3f4f",
 	left = "#bca1f6",
 	right = "#a3e7fc",
 	foreground = "#ffffff",
 	bg = 'dark',
 	normal_black = "#000000",
 	normal_red = "#ff5555",
 	normal_green = "#50fa7b",
 	normal_yellow = "#f1fa8c",
 	normal_blue = "#bd93f9",
 	normal_magenta = "#ff79c6",
 	normal_cyan = "#8be9fd",
 	normal_white = "#bbbbbb",
 	bright_black = "#555555",
 	bright_red = "#ff5555",
 	bright_green = "#50fa7b",
 	bright_yellow = "#f1fa8c",
 	bright_blue = "#caa9fa",
 	bright_magenta = "#ff79c6",
 	bright_cyan = "#8be9fd",
 	bright_white = "#ffffff",
}