return {
 	background = "#1b1718",
 	accent = "#005386",
 	foreground = "#ffffff",
 	bg = 'dark',
 	normal_black = "#616161",
 	normal_red = "#ff8272",
 	normal_green = "#b4fa72",
 	normal_yellow = "#fefdc2",
 	normal_blue = "#a5d5fe",
 	normal_magenta = "#ff8ffd",
 	normal_cyan = "#d0d1fe",
 	normal_white = "#f1f1f1",
 	bright_black = "#8e8e8e",
 	bright_red = "#ffc4bd",
 	bright_green = "#d6fcb9",
 	bright_yellow = "#fefdd5",
 	bright_blue = "#c1e3fe",
 	bright_magenta = "#ffb1fe",
 	bright_cyan = "#e5e6fe",
 	bright_white = "#feffff",
}