return {
	bright_blue = "#caa9fa",
	bright_cyan = "#8be9fd",
	bright_green = "#50fa7b",
	bright_magenta = "#ff79c6",
	bright_red = "#ff5555",
	bright_white = "#ffffff",
	bright_yellow = "#f1fa8c",
	normal_blue = "#bd93f9",
	normal_cyan = "#8be9fd",
	normal_green = "#50fa7b",
	normal_magenta = "#ff79c6",
	normal_red = "#ff5555",
	normal_white = "#bbbbbb",
	normal_yellow = "#f1fa8c",
}
